# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    build_app(workspace: "ZenID.xcworkspace", scheme: "ZenIDDemo")
    upload_to_testflight
  end

  lane :firebase do
    build_app(workspace: "ZenID.xcworkspace", scheme: "ZenIDDemo", export_method: "ad-hoc")
    firebase_app_distribution(
      app: "1:308002022528:ios:36531d62e268b7432df265",
      testers: "ffogaras@trask.cz, enrico@nubtron.com",
      release_notes_file: "CHANGELOG.md",
    )
  end
end
