# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    build_app(workspace: "ZenID.xcworkspace", scheme: "ZenIDDemo")
    upload_to_testflight
  end


  desc "Download certificate and provisioning profile from apple"
  lane :setup do
    get_certificates
    get_provisioning_profile
  end

  desc "Upload testing build to firebase App Distribution"
  lane :firebase do
    versionNumber = get_version_number_from_xcodeproj(scheme: "ZenIDDemo")
    buildNumber =  number_of_commits
    ipaName = "ZenIDDemo_#{versionNumber}(#{buildNumber})"

    increment_build_number_in_plist(
      build_number: "#{number_of_commits}",
      xcodeproj: "ZenIDDemo.xcodeproj"
    )

    build_app(
      workspace: "ZenID.xcworkspace",
      scheme: "ZenIDDemo",
      export_method: "ad-hoc",
      output_name: ipaName,
      export_options: {
        provisioningProfiles: {
        "cz.trask.ZenID" => "Distriburion: ZenID Demo AdHoc"
        }
      }
    )

    firebase_app_distribution(
      app: "1:308002022528:ios:36531d62e268b7432df265",
      groups: "Inhouse",
      release_notes_file: "CHANGELOG.md",
      service_credentials_file: ".firebase-service-account.json"
    )
  end
end
