name: iOS starter workflow

on:
  push:
    branches: [ "release" ]
  pull_request:
    branches: [ "release" ]

jobs:
  build:
    name: Build and Test release
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        run: |
          gem install bundle
          bundle install
          bundle exec fastlane setup
      - name: Build
        run: |
          bundle exec fastlane build
      - name: Distribute
        run: |
          bundle exec fastlane firebase
